### ISSUE TITLE
判断回文数

### ISSUE THREAD

**Issue by kaikai-sk** [Blankj/awesome-java-leetcode#18]
class Solution {
    public boolean isPalindrome(int x) {
        if (x < 0 || (x != 0 && x % 10 == 0)) return false;
        int halfReverseX = 0;
        while (x > halfReverseX) {
            halfReverseX = halfReverseX * 10 + x % 10;
            x /= 10;
        }
        return halfReverseX == x || halfReverseX / 10 == x;
    }
}

什么时候会走halfReverseX == x  这条return 路径呢？？

**Comment by Blankj** [comment]
x为偶数长度的数字时，要自己多思考哈

**Comment by kaikai-sk** [comment]
一时没想出来。
该多吃点核桃补补脑了
