### ISSUE TITLE
004题目的疑问

### ISSUE THREAD

**Issue by LomoLin** [Blankj/awesome-java-leetcode#5]
你好，在算法004的题目中，既然是两个已经排序好的数组中，要取这两个数组的中位数，为什么不直接去第一个数组的中位数，再去第二个数组的中位数，最后取这两个中位数的平均值，不就是结果了吗？感觉看004的算法有点复杂。我这样的算法是否有什么问题，还望告知，谢谢！

**Comment by Blankj** [comment]
那你是想太少了，比如 `{1}`，`{1, 2}` 你的结果对吗，而且题目要求时间复杂度是 `O(log (m+n))`
