### ISSUE TITLE
第一题思路一的解有问题

### ISSUE THREAD

**Issue by gaoyl87** [Blankj/awesome-java-leetcode#7]
刚刚开始看leetcode，大家共勉。
第一题思路一
for (int i = 0; i < nums.length; ++i) {
是否应该是 i < nums.length - 1会更好

**Comment by Blankj** [comment]
不要钻牛角尖啦，那我还能说你每次循环都去算 `nums.length -1` 还消耗性能呢，我多走一重无效的 for 循环也比你多次运算好吧从最终生成的汇编来说，主要是思路，我也没说我的是最优解，优化得不能再优化，最终 AC 了，那这种思路就是对的，你要是这么钻，那我也没办法。
